run:
  timeout: 5m
  concurrency: 4
  tests: false

issues:
  exclude-rules:
    - source: "^//go:generate"
      linters: [funlen , lll , varnamelen, err113, dupword]
    - path: _test\.go
      linters: [funlen , lll , varnamelen, err113, dupword]